/* {{{ License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *///}}}
// :indentSize=4:lineSeparator=\n:noTabs=false:tabSize=4:folding=explicit:collapseFolds=0:
package org.mathpiper.ui.gui.calculator;

import java.beans.PropertyVetoException;
import org.mathpiper.interpreters.Interpreter;
import org.mathpiper.interpreters.Interpreters;
import org.mathpiper.interpreters.EvaluationResponse;

/**
 *
 * @author  tkosan
 */
public class CalculatorPanel extends javax.swing.JPanel
{
    //private StandardFileOutputStream stdoutput = new StandardFileOutputStream(System.out);
    private Interpreter mathpiper;
    private StringBuilder enteredText = new StringBuilder();

    /** Creates new form CalculatorPanel */
    public CalculatorPanel()
    {
        initComponents();
	setBackground(new java.awt.Color(255,255,255));

        mathpiper = Interpreters.getSynchronousInterpreter();
        
       /*
         try
        {
        jInternalFrame1.setIcon(true);
        }
        catch(Exception e)
        {
            
        }*/
    }

    public CalculatorPanel(String docBase)
    {
        this.initComponents();
	setBackground(new java.awt.Color(255,255,255));

        mathpiper = Interpreters.getSynchronousInterpreter(docBase);

    }//end constructor.

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        zeroButton = new javax.swing.JButton();
        decimalPointButton = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        allClearButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        display = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(new java.awt.BorderLayout());

       // jLabel1.setText("MathRider Super Scientific Calculator (http://mathrider.org)");
        //add(jLabel1, java.awt.BorderLayout.NORTH);

       // jLabel2.setText("V.01");
        //add(jLabel2, java.awt.BorderLayout.SOUTH);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Keypad");
        jInternalFrame1.setVisible(true);

        zeroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/zero.gif"))); // NOI18N
        zeroButton.setActionCommand("0");
        zeroButton.setMaximumSize(new java.awt.Dimension(27, 27));
        zeroButton.setMinimumSize(new java.awt.Dimension(27, 27));
        zeroButton.setPreferredSize(new java.awt.Dimension(27, 27));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonsymbolButtonActionPerformed(evt);
            }
        });

        decimalPointButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        decimalPointButton.setText(".");
        decimalPointButton.setMaximumSize(new java.awt.Dimension(27, 27));
        decimalPointButton.setMinimumSize(new java.awt.Dimension(27, 27));
        decimalPointButton.setPreferredSize(new java.awt.Dimension(27, 27));
        decimalPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPointButtonsymbolButtonActionPerformed(evt);
            }
        });

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/exp.gif"))); // NOI18N
        jButton23.setActionCommand("^");
        jButton23.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton23.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton23.setPreferredSize(new java.awt.Dimension(27, 27));

        oneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/one.gif"))); // NOI18N
        oneButton.setActionCommand("1");
        oneButton.setMaximumSize(new java.awt.Dimension(27, 27));
        oneButton.setMinimumSize(new java.awt.Dimension(27, 27));
        oneButton.setPreferredSize(new java.awt.Dimension(27, 27));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonsymbolButtonActionPerformed(evt);
            }
        });

        twoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/two.gif"))); // NOI18N
        twoButton.setActionCommand("2");
        twoButton.setMaximumSize(new java.awt.Dimension(27, 27));
        twoButton.setMinimumSize(new java.awt.Dimension(27, 27));
        twoButton.setPreferredSize(new java.awt.Dimension(27, 27));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonsymbolButtonActionPerformed(evt);
            }
        });

        threeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/three.gif"))); // NOI18N
        threeButton.setActionCommand("3");
        threeButton.setMaximumSize(new java.awt.Dimension(27, 27));
        threeButton.setMinimumSize(new java.awt.Dimension(27, 27));
        threeButton.setPreferredSize(new java.awt.Dimension(27, 27));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonsymbolButtonActionPerformed(evt);
            }
        });

        fourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/four.gif"))); // NOI18N
        fourButton.setActionCommand("4");
        fourButton.setMaximumSize(new java.awt.Dimension(27, 27));
        fourButton.setMinimumSize(new java.awt.Dimension(27, 27));
        fourButton.setPreferredSize(new java.awt.Dimension(27, 27));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonsymbolButtonActionPerformed(evt);
            }
        });

        fiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/five.gif"))); // NOI18N
        fiveButton.setActionCommand("5");
        fiveButton.setMaximumSize(new java.awt.Dimension(27, 27));
        fiveButton.setMinimumSize(new java.awt.Dimension(27, 27));
        fiveButton.setPreferredSize(new java.awt.Dimension(27, 27));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonsymbolButtonActionPerformed(evt);
            }
        });

        sixButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/six.gif"))); // NOI18N
        sixButton.setActionCommand("6");
        sixButton.setMaximumSize(new java.awt.Dimension(27, 27));
        sixButton.setMinimumSize(new java.awt.Dimension(27, 27));
        sixButton.setPreferredSize(new java.awt.Dimension(27, 27));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonsymbolButtonActionPerformed(evt);
            }
        });

        sevenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/seven.gif"))); // NOI18N
        sevenButton.setActionCommand("7");
        sevenButton.setMaximumSize(new java.awt.Dimension(27, 27));
        sevenButton.setMinimumSize(new java.awt.Dimension(27, 27));
        sevenButton.setPreferredSize(new java.awt.Dimension(27, 27));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonsymbolButtonActionPerformed(evt);
            }
        });

        eightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/eight.gif"))); // NOI18N
        eightButton.setActionCommand("8");
        eightButton.setMaximumSize(new java.awt.Dimension(27, 27));
        eightButton.setMinimumSize(new java.awt.Dimension(27, 27));
        eightButton.setPreferredSize(new java.awt.Dimension(27, 27));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonsymbolButtonActionPerformed(evt);
            }
        });

        nineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/nine.gif"))); // NOI18N
        nineButton.setActionCommand("9");
        nineButton.setMaximumSize(new java.awt.Dimension(27, 27));
        nineButton.setMinimumSize(new java.awt.Dimension(27, 27));
        nineButton.setPreferredSize(new java.awt.Dimension(27, 27));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonsymbolButtonActionPerformed(evt);
            }
        });

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/ans.gif"))); // NOI18N
        jButton24.setActionCommand("ans");
        jButton24.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton24.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton24.setPreferredSize(new java.awt.Dimension(27, 27));

        equals.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        equals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/equals.gif"))); // NOI18N
        equals.setActionCommand("equals");
        equals.setMaximumSize(new java.awt.Dimension(27, 27));
        equals.setMinimumSize(new java.awt.Dimension(27, 27));
        equals.setPreferredSize(new java.awt.Dimension(27, 27));
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        additionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/plus.gif"))); // NOI18N
        additionButton.setActionCommand("+");
        additionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        additionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        additionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonsymbolButtonActionPerformed(evt);
            }
        });

        subtractionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/minus.gif"))); // NOI18N
        subtractionButton.setActionCommand("-");
        subtractionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        subtractionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        subtractionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonsymbolButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/del.gif"))); // NOI18N
        deleteButton.setActionCommand("del");
        deleteButton.setMaximumSize(new java.awt.Dimension(27, 27));
        deleteButton.setMinimumSize(new java.awt.Dimension(27, 27));
        deleteButton.setPreferredSize(new java.awt.Dimension(27, 27));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        allClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/ac.gif"))); // NOI18N
        allClearButton.setActionCommand("ac");
        allClearButton.setMaximumSize(new java.awt.Dimension(27, 27));
        allClearButton.setMinimumSize(new java.awt.Dimension(27, 27));
        allClearButton.setPreferredSize(new java.awt.Dimension(27, 27));
        allClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/times.gif"))); // NOI18N
        multiplicationButton.setActionCommand("*");
        multiplicationButton.setMaximumSize(new java.awt.Dimension(27, 27));
        multiplicationButton.setMinimumSize(new java.awt.Dimension(27, 27));
        multiplicationButton.setPreferredSize(new java.awt.Dimension(27, 27));
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonsymbolButtonActionPerformed(evt);
            }
        });

        divisionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/ui/gui/calculator/resources/div.gif"))); // NOI18N
        divisionButton.setActionCommand("/");
        divisionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        divisionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        divisionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonsymbolButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(allClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jInternalFrame1.setBounds(90, 140, 270, 220);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Display");
        jInternalFrame2.setVisible(true);

        display.setFont(new java.awt.Font("DejaVu Sans 14", 0, 18)); // NOI18N
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMouseClicked(evt);
            }
        });
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                displayKeyReleased(evt);
            }
        });
        jInternalFrame2.getContentPane().add(display, java.awt.BorderLayout.NORTH);

        jInternalFrame2.setBounds(10, 30, 430, 80);
        jDesktopPane1.add(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

public EvaluationResponse evaluate(String expression)
{
    EvaluationResponse evaluationResponse;

    evaluationResponse = mathpiper.evaluate(expression + ";");

    return evaluationResponse;
}//end method.


private void zeroButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_zeroButtonsymbolButtonActionPerformed

private void decimalPointButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPointButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_decimalPointButtonsymbolButtonActionPerformed

private void oneButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_oneButtonsymbolButtonActionPerformed

private void twoButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_twoButtonsymbolButtonActionPerformed

private void threeButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_threeButtonsymbolButtonActionPerformed

private void fourButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_fourButtonsymbolButtonActionPerformed

private void fiveButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_fiveButtonsymbolButtonActionPerformed

private void sixButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_sixButtonsymbolButtonActionPerformed

private void sevenButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_sevenButtonsymbolButtonActionPerformed

private void eightButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_eightButtonsymbolButtonActionPerformed

private void nineButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_nineButtonsymbolButtonActionPerformed

private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
    EvaluationResponse evaluationResponse;

    evaluationResponse = mathpiper.evaluate("N(" + enteredText.toString() + ");");
    enteredText.delete(0, enteredText.length());
    display.setText(evaluationResponse.getResult());


}//GEN-LAST:event_equalsButtonActionPerformed

private void additionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_additionButtonsymbolButtonActionPerformed

private void subtractionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_subtractionButtonsymbolButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    if (enteredText.length() != 0)
    {
        enteredText.deleteCharAt(enteredText.length() - 1);
        display.setText(enteredText.toString());
    }
}//GEN-LAST:event_deleteButtonActionPerformed

private void allClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearButtonActionPerformed
    enteredText.delete(0, enteredText.length());
    display.setText(enteredText.toString());
}//GEN-LAST:event_allClearButtonActionPerformed

private void multiplicationButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_multiplicationButtonsymbolButtonActionPerformed

private void divisionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonsymbolButtonActionPerformed
    String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_divisionButtonsymbolButtonActionPerformed

private void displayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyPressed
    evt.consume();
}//GEN-LAST:event_displayKeyPressed

private void displayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyReleased
    evt.consume();
}//GEN-LAST:event_displayKeyReleased

private void displayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyTyped
    evt.consume();
}//GEN-LAST:event_displayKeyTyped

private void displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_displayMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JButton allClearButton;
    private javax.swing.JButton decimalPointButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField display;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equals;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
