/*
 * CalculatorPanel.java
 *
 * Created on November 28, 2008, 12:12 AM
 */

package org.mathpiper.gui.calculator;

import org.mathpiper.Interpreter;
import org.mathpiper.exceptions.MathPiperException;
import org.mathpiper.io.StandardFileOutputStream;

/**
 *
 * @author  tkosan
 */
public class CalculatorPanel extends javax.swing.JPanel {
       private StandardFileOutputStream stdoutput = new StandardFileOutputStream(System.out);
    private Interpreter mathpiper = new Interpreter(stdoutput);
    private StringBuilder enteredText = new StringBuilder();
    /** Creates new form CalculatorPanel */
    public CalculatorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        zeroButton = new javax.swing.JButton();
        decimalPointButton = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        allClearButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();

        display.setFont(new java.awt.Font("DejaVu Sans 14", 0, 12));

        zeroButton.setText("0");
        zeroButton.setMaximumSize(new java.awt.Dimension(27, 27));
        zeroButton.setMinimumSize(new java.awt.Dimension(27, 27));
        zeroButton.setPreferredSize(new java.awt.Dimension(27, 27));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonsymbolButtonActionPerformed(evt);
            }
        });

        decimalPointButton.setText(".");
        decimalPointButton.setMaximumSize(new java.awt.Dimension(27, 27));
        decimalPointButton.setMinimumSize(new java.awt.Dimension(27, 27));
        decimalPointButton.setPreferredSize(new java.awt.Dimension(27, 27));
        decimalPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPointButtonsymbolButtonActionPerformed(evt);
            }
        });

        jButton23.setText("EXP");
        jButton23.setActionCommand("^");
        jButton23.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton23.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton23.setPreferredSize(new java.awt.Dimension(27, 27));

        oneButton.setText("1");
        oneButton.setMaximumSize(new java.awt.Dimension(27, 27));
        oneButton.setMinimumSize(new java.awt.Dimension(27, 27));
        oneButton.setPreferredSize(new java.awt.Dimension(27, 27));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonsymbolButtonActionPerformed(evt);
            }
        });

        twoButton.setText("2");
        twoButton.setMaximumSize(new java.awt.Dimension(27, 27));
        twoButton.setMinimumSize(new java.awt.Dimension(27, 27));
        twoButton.setPreferredSize(new java.awt.Dimension(27, 27));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonsymbolButtonActionPerformed(evt);
            }
        });

        threeButton.setText("3");
        threeButton.setMaximumSize(new java.awt.Dimension(27, 27));
        threeButton.setMinimumSize(new java.awt.Dimension(27, 27));
        threeButton.setPreferredSize(new java.awt.Dimension(27, 27));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonsymbolButtonActionPerformed(evt);
            }
        });

        fourButton.setText("4");
        fourButton.setMaximumSize(new java.awt.Dimension(27, 27));
        fourButton.setMinimumSize(new java.awt.Dimension(27, 27));
        fourButton.setPreferredSize(new java.awt.Dimension(27, 27));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonsymbolButtonActionPerformed(evt);
            }
        });

        fiveButton.setText("5");
        fiveButton.setMaximumSize(new java.awt.Dimension(27, 27));
        fiveButton.setMinimumSize(new java.awt.Dimension(27, 27));
        fiveButton.setPreferredSize(new java.awt.Dimension(27, 27));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonsymbolButtonActionPerformed(evt);
            }
        });

        sixButton.setText("6");
        sixButton.setMaximumSize(new java.awt.Dimension(27, 27));
        sixButton.setMinimumSize(new java.awt.Dimension(27, 27));
        sixButton.setPreferredSize(new java.awt.Dimension(27, 27));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonsymbolButtonActionPerformed(evt);
            }
        });

        sevenButton.setText("7");
        sevenButton.setMaximumSize(new java.awt.Dimension(27, 27));
        sevenButton.setMinimumSize(new java.awt.Dimension(27, 27));
        sevenButton.setPreferredSize(new java.awt.Dimension(27, 27));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonsymbolButtonActionPerformed(evt);
            }
        });

        eightButton.setText("8");
        eightButton.setMaximumSize(new java.awt.Dimension(27, 27));
        eightButton.setMinimumSize(new java.awt.Dimension(27, 27));
        eightButton.setPreferredSize(new java.awt.Dimension(27, 27));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonsymbolButtonActionPerformed(evt);
            }
        });

        nineButton.setText("9");
        nineButton.setMaximumSize(new java.awt.Dimension(27, 27));
        nineButton.setMinimumSize(new java.awt.Dimension(27, 27));
        nineButton.setPreferredSize(new java.awt.Dimension(27, 27));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonsymbolButtonActionPerformed(evt);
            }
        });

        jButton24.setIcon(new javax.swing.ImageIcon("/home/tkosan/temp/textogif/test.gif")); // NOI18N
        jButton24.setMaximumSize(new java.awt.Dimension(27, 27));
        jButton24.setMinimumSize(new java.awt.Dimension(27, 27));
        jButton24.setPreferredSize(new java.awt.Dimension(27, 27));

        equals.setText("=");
        equals.setMaximumSize(new java.awt.Dimension(27, 27));
        equals.setMinimumSize(new java.awt.Dimension(27, 27));
        equals.setPreferredSize(new java.awt.Dimension(27, 27));
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        additionButton.setText("+");
        additionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        additionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        additionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonsymbolButtonActionPerformed(evt);
            }
        });

        subtractionButton.setActionCommand("-");
        subtractionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        subtractionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        subtractionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonsymbolButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DEL");
        deleteButton.setMaximumSize(new java.awt.Dimension(27, 27));
        deleteButton.setMinimumSize(new java.awt.Dimension(27, 27));
        deleteButton.setPreferredSize(new java.awt.Dimension(27, 27));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        allClearButton.setText("AC");
        allClearButton.setMaximumSize(new java.awt.Dimension(27, 27));
        allClearButton.setMinimumSize(new java.awt.Dimension(27, 27));
        allClearButton.setPreferredSize(new java.awt.Dimension(27, 27));
        allClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mathpiper/gui/calculator/resources/multiply.gif"))); // NOI18N
        multiplicationButton.setActionCommand("*");
        multiplicationButton.setMaximumSize(new java.awt.Dimension(27, 27));
        multiplicationButton.setMinimumSize(new java.awt.Dimension(27, 27));
        multiplicationButton.setPreferredSize(new java.awt.Dimension(27, 27));
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonsymbolButtonActionPerformed(evt);
            }
        });

        divisionButton.setActionCommand("/");
        divisionButton.setMaximumSize(new java.awt.Dimension(27, 27));
        divisionButton.setMinimumSize(new java.awt.Dimension(27, 27));
        divisionButton.setPreferredSize(new java.awt.Dimension(27, 27));
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonsymbolButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(decimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(decimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(allClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(120, 120, 120)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void zeroButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_zeroButtonsymbolButtonActionPerformed

private void decimalPointButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPointButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_decimalPointButtonsymbolButtonActionPerformed

private void oneButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_oneButtonsymbolButtonActionPerformed

private void twoButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_twoButtonsymbolButtonActionPerformed

private void threeButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_threeButtonsymbolButtonActionPerformed

private void fourButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_fourButtonsymbolButtonActionPerformed

private void fiveButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_fiveButtonsymbolButtonActionPerformed

private void sixButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_sixButtonsymbolButtonActionPerformed

private void sevenButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_sevenButtonsymbolButtonActionPerformed

private void eightButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_eightButtonsymbolButtonActionPerformed

private void nineButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_nineButtonsymbolButtonActionPerformed

private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
String result;
            try
            {
                result = mathpiper.evaluate("N(" + enteredText.toString() +");");
                enteredText.delete(0, enteredText.length());
                display.setText(result);
                
            } catch (MathPiperException pe)
            {
                pe.printStackTrace();
            }
}//GEN-LAST:event_equalsButtonActionPerformed

private void additionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_additionButtonsymbolButtonActionPerformed

private void subtractionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_subtractionButtonsymbolButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
if(enteredText.length() != 0)
    {
        enteredText.deleteCharAt(enteredText.length()-1);
        display.setText(enteredText.toString());
    }
}//GEN-LAST:event_deleteButtonActionPerformed

private void allClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearButtonActionPerformed
enteredText.delete(0,enteredText.length());
    display.setText(enteredText.toString());
}//GEN-LAST:event_allClearButtonActionPerformed

private void multiplicationButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_multiplicationButtonsymbolButtonActionPerformed

private void divisionButtonsymbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonsymbolButtonActionPerformed
String symbol = evt.getActionCommand();

    enteredText.append(symbol);
    display.setText(enteredText.toString());
}//GEN-LAST:event_divisionButtonsymbolButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JButton allClearButton;
    private javax.swing.JButton decimalPointButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField display;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equals;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables

}
