/* {{{ License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */ //}}}

// :indentSize=4:lineSeparator=\n:noTabs=false:tabSize=4:folding=explicit:collapseFolds=0:
package org.mathpiper.scripts;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author tkosan
 */
public class ScriptsToClasses {

    private java.io.File scriptsDir;
    private java.io.FileWriter logFile;

    public void classify(String scriptsDirectory, String outputDirectory) {
        StringBuilder s = new StringBuilder();
        s.append("package org.mathpiper.scripts;\n");
        s.append("\n\n//*** This file was generated by the ScriptsToClasses class.  Do not edit it. ***\n\n");
        s.append("import java.io.ByteArrayInputStream;\n");
        s.append("import java.util.HashMap;\n");
        s.append("import java.util.Map;\n");
        s.append("import java.io.InputStream;\n");
        s.append("\n");
        s.append("public class Scripts\n");
        s.append("{\n");
        s.append("\n");
        s.append("private static Map scriptsMap = new HashMap();\n");
        s.append("\n");
        s.append("static{\n");


        try {

            logFile = new java.io.FileWriter("scripts_to_classes.log");


            scriptsDir = new java.io.File(scriptsDirectory);

            if (scriptsDir.exists()) {
                java.io.File[] packagesDirectory = scriptsDir.listFiles(new java.io.FilenameFilter() {

                    public boolean accept(java.io.File file, String name) {
                        if (name.endsWith(".rep")) {
                            return (true);
                        } else {
                            return (false);
                        }
                    }
                });


                String output;
                for (int x = 0; x < packagesDirectory.length; x++) {
                    File packageDirectoryFile = packagesDirectory[x];
                    String packageDirectoryFileName = packageDirectoryFile.getName();
                    System.out.println(packageDirectoryFileName);

                    //Create package directory
                    String dirNameRep = packageDirectoryFileName;
                    String newPackageName = dirNameRep.substring(0, dirNameRep.indexOf("."));
                    String newPackagePath = outputDirectory + newPackageName;
                    File newPackageFile = new File(newPackagePath);
                    Boolean directoryCreated = newPackageFile.mkdir();


                    //Place class files in package dir


                    if (packageDirectoryFile.exists()) {
                        java.io.File[] packageDirectory = packageDirectoryFile.listFiles(new java.io.FilenameFilter() {

                            public boolean accept(java.io.File file, String name) {
                                if (name.endsWith(".mpi") || name.endsWith(".def")) {
                                    return (true);
                                } else {
                                    return (false);
                                }
                            }
                        });



                        //Process a package.
                        StringBuilder f = new StringBuilder();
                        String classNameUpper = null;
                        for (int x2 = 0; x2 < packageDirectory.length; x2++) {
                            File scriptFile = packageDirectory[x2];
                            System.out.println("   " + scriptFile.getName());


                            f.append("package org.mathpiper.scripts." + newPackageName + ";\n");
                            f.append("\n\n//*** This file was generated by the ScriptsToClasses class.  Do not edit it. ***\n\n");
                            f.append("public class ");
                            String rawScriptName = scriptFile.getName();
                            String classNameLower = rawScriptName.substring(0, rawScriptName.indexOf("."));
                            String firstChar = classNameLower.substring(0, 1);
                            firstChar = firstChar.toUpperCase();
                            classNameUpper = firstChar + classNameLower.substring(1);


                            //String sc = readFileAsString(scriptFile);

                            byte[] bytes = getBytesFromFile(scriptFile);
                            String p = printByteArray(bytes);

                            p = p.replaceAll("0x2F,0x2A,.*?0x2A,0x2F,", ""); //Remove all multiline comments.
                            p = p.replaceAll("0x0D,", ""); //Remove all carriage returns.
                            p = p.replaceAll("0x2F,0x2F,.*?0x0A,", ""); //Remove all single line comments.

                            //p = p.replaceAll("(0x20,|(0x22,.*?0x22,))",""); //Replace spaces.
                            //p = p.replaceAll("0x0A,", ""); //Remove all newlines.





                            String scriptFileName = scriptFile.getName();
                            String scriptFileNameOnly = scriptFileName.substring(0, scriptFileName.indexOf("."));
                            if (scriptFileName.endsWith(".def")) {
                                scriptFileNameOnly = scriptFileNameOnly + "_def";
                                classNameUpper = classNameUpper + "Def";
                            }
                            f.append(classNameUpper + "{\n");
                            f.append("static final byte[] ");
                            f.append(scriptFileNameOnly);
                            s.append("scriptsMap.put(\"" + packageDirectoryFileName + "/" + scriptFileName + "\"," + classNameUpper + "." + scriptFileNameOnly + ");\n");
                            f.append(" = ");
                            f.append(p);
                            f.append(";\n");
                            f.append("}\n");
                            String pp = newPackageFile.getPath();
                            writeStringToFile(f.toString(), newPackageFile.getPath() + File.separator + classNameUpper + ".java");
                        }//end for.




                    }//end if.

                }//end for.
                s.append("}\n\n\n");
                s.append("public static java.io.InputStream getScriptStream(String scriptName)\n");
                s.append("    {\n");
                s.append("        return new java.io.ByteArrayInputStream((byte[])scriptsMap.get(scriptName));\n");
                s.append("    }\n");
                s.append("}\n");

                writeStringToFile(s.toString(), outputDirectory + "Scripts.java");

                System.out.println(s.toString());

            } else {
                System.out.println("\nDirectory " + scriptsDirectory + "does not exist.\n");
            }

            logFile.close();

        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

    }//end method.

    public static void main(String[] args) {

        String scriptsDirectory;

        if (args.length > 0) {
            scriptsDirectory = args[0];
        } else {
            scriptsDirectory = "/home/tkosan/NetBeansProjects/mathpiper/scripts";
        }
        //String outputDirectory = "/home/tkosan/NetBeansProjects/mathpiper/src/org/mathpiper/scripts/";
        String outputDirectory = "/home/tkosan/temp/mathpiper/org/mathpiper/scripts/";

        ScriptsToClasses scripts = new ScriptsToClasses();
        scripts.classify(scriptsDirectory, outputDirectory);

    }//end main

    /** @param filePath the name of the file to open. Not sure if it can accept URLs or just filenames. Path handling could be better, and buffer sizes are hardcoded
     */
    private static String readFileAsString(File file) throws IOException {
        StringBuilder fileData = new StringBuilder(1000);
        BufferedReader reader = new BufferedReader(
                new FileReader(file));
        char[] buf = new char[1024];
        int numRead = 0;
        while ((numRead = reader.read(buf)) != -1) {
            String readData = String.valueOf(buf, 0, numRead);
            fileData.append(readData);
            buf = new char[1024];
        }
        reader.close();
        return fileData.toString();
    }//end method.

    private static void writeStringToFile(String string, String fileName) throws IOException {
        try {

            BufferedWriter out = new BufferedWriter(new FileWriter(fileName));


            //someText.replaceAll("\n", System.getProperty("line.separator"));

            out.write(string);
            out.close();

        } catch (IOException e) {

            System.out.println("Exception ");

        }
    }//end method.

    public static byte[] getBytesFromFile(File file) throws IOException {
        InputStream is = new FileInputStream(file);

        // Get the size of the file
        long length = file.length();

        if (length > Integer.MAX_VALUE) {
            // File is too large
        }

        // Create the byte array to hold the data
        byte[] bytes = new byte[(int) length];

        // Read in the bytes
        int offset = 0;
        int numRead = 0;
        while (offset < bytes.length && (numRead = is.read(bytes, offset, bytes.length - offset)) >= 0) {
            offset += numRead;
        }

        // Ensure all the bytes have been read in
        if (offset < bytes.length) {
            throw new IOException("Could not completely read file " + file.getName());
        }

        // Close the input stream and return bytes
        is.close();
        return bytes;
    }

    private static String printByteArray(byte[] bytes) {
        /*java_code = []
        java_code.append("{")
        for byte in bytes:
        if byte > 127:
        byte = (byte - 128) + -128
        java_code.append(str(byte))
        java_code.append(",")
        del java_code[-1]
        java_code.append("}")*/


        StringBuilder b = new StringBuilder();
        b.append("{");
        for (int x = 0; x < bytes.length; x++) {
            byte bite = bytes[x];
            if (bite > 127) {
                //bite = (bite - 128) + -128;
                System.out.println("Encountered a byte that was greater than 127.");
            }

            String num = Integer.toHexString(bite);
            num = num.toUpperCase();
            if (num.length() < 2) {
                num = "0" + num;
            }
            num = "0x" + num;

            b.append(num);
            b.append(",");

        }//end for.
        b.delete(b.length() - 1, b.length());
        b.append("}");
        return b.toString();


    }
}//end class.



